# Join Statements - Lab

## Introduction

In this lab, you'll practice your knowledge of `JOIN` statements, using various types of joins and various methods for specifying the links between them.

## Objectives

You will be able to:

* Write SQL queries that make use of various types of joins
* Compare and contrast the various types of joins
* Discuss how primary and foreign keys are used in SQL
* Decide and perform whichever type of join is best for retrieving desired data

## CRM ERD

In this lab, you'll use the same customer relationship management (CRM) database that you saw from the previous lesson.
<img src='https://curriculum-content.s3.amazonaws.com/data-science/images/Database-Schema.png' width="600">

## Connecting to the Database
Import the necessary packages and connect to the database `'data.sqlite'`.

In [2]:
# Your code here
import sqlite3
import pandas as pd

In [3]:
con=sqlite3.connect('data.sqlite')

In [4]:
cur=con.cursor()

## Select the names of all employees in Boston 

Hint: join the employees and offices tables. Select the first and last name.

In [5]:
q=('''SELECT * FROM employees''')
pd.read_sql(q,con)

,employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle
0,1002,Murphy,Diane,x5800,dmurphy@classicmodelcars.com,1,,President
1,1056,Patterson,Mary,x4611,mpatterso@classicmodelcars.com,1,1002,VP Sales
2,1076,Firrelli,Jeff,x9273,jfirrelli@classicmodelcars.com,1,1002,VP Marketing
3,1088,Patterson,William,x4871,wpatterson@classicmodelcars.com,6,1056,Sales Manager (APAC)
4,1102,Bondur,Gerard,x5408,gbondur@classicmodelcars.com,4,1056,Sale Manager (EMEA)
5,1143,Bow,Anthony,x5428,abow@classicmodelcars.com,1,1056,Sales Manager (NA)
6,1165,Jennings,Leslie,x3291,ljennings@classicmodelcars.com,1,1143,Sales Rep
7,1166,Thompson,Leslie,x4065,lthompson@classicmodelcars.com,1,1143,Sales Rep
8,1188,Firrelli,Julie,x2173,jfirrelli@classicmodelcars.com,2,1143,Sales Rep
9,1216,Patterson,Steve,x4334,spatterson@classicmodelcars.com,2,1143,Sales Rep
10,1286,Tseng,Foon Yue,x2248,ftseng@classicmodelcars.com,3,1143,Sales Rep
11,1323,Vanauf,George,x4102,gvanauf@classicmodelcars.com,3,1143,Sales Rep
12,1337,Bondur,Loui,x6493,lbondur@classicmodelcars.com,4,1102,Sales Rep
13,1370,Hernandez,Gerard,x2028,ghernande@classicmodelcars.com,4,1102,Sales Rep
14,1401,Castillo,Pamela,x2759,pcastillo@classicmodelcars.com,4,1102,Sales Rep
15,1501,Bott,Larry,x2311,lbott@classicmodelcars.com,7,1102,Sales Rep
16,1504,Jones,Barry,x102,bjones@classicmodelcars.com,7,1102,Sales Rep
17,1611,Fixter,Andy,x101,afixter@classicmodelcars.com,6,1088,Sales Rep
18,1612,Marsh,Peter,x102,pmarsh@classicmodelcars.com,6,1088,Sales Rep
19,1619,King,Tom,x103,tking@classicmodelcars.com,6,1088,Sales Rep
20,1621,Nishi,Mami,x101,mnishi@classicmodelcars.com,5,1056,Sales Rep
21,1625,Kato,Yoshimi,x102,ykato@classicmodelcars.com,5,1621,Sales Rep
22,1702,Gerard,Martin,x2312,mgerard@classicmodelcars.com,4,1102,Sales Rep

In [6]:
q=('''SELECT * FROM offices''')
pd.read_sql(q,con)

,officeCode,city,phone,addressLine1,addressLine2,state,country,postalCode,territory
0,1,San Francisco,+1 650 219 4782,100 Market Street,Suite 300,CA,USA,94080,NA
1,2,Boston,+1 215 837 0825,1550 Court Place,Suite 102,MA,USA,02107,NA
2,3,NYC,+1 212 555 3000,523 East 53rd Street,apt. 5A,NY,USA,10022,NA
3,4,Paris,+33 14 723 4404,43 Rue Jouffroy D'abbans,,,France,75017,EMEA
4,5,Tokyo,+81 33 224 5000,4-1 Kioicho,,Chiyoda-Ku,Japan,102-8578,Japan
5,6,Sydney,+61 2 9264 2451,5-11 Wentworth Avenue,Floor #2,,Australia,NSW 2010,APAC
6,7,London,+44 20 7877 2041,25 Old Broad Street,Level 7,,UK,EC2N 1HN,EMEA
7,27,Boston,+1 977 299 8345,105 Cambridge Street,,MA,USA,02331,NA

In [7]:
# Your code here
q='''SELECT DISTINCT firstName, lastName FROM employees e JOIN offices WHERE city='Boston' ''' 
pd.read_sql(q,con)

   firstName   lastName
0      Diane     Murphy
1       Mary  Patterson
2       Jeff   Firrelli
3    William  Patterson
4     Gerard     Bondur
5    Anthony        Bow
6     Leslie   Jennings
7     Leslie   Thompson
8      Julie   Firrelli
9      Steve  Patterson
10  Foon Yue      Tseng
11    George     Vanauf
12      Loui     Bondur
13    Gerard  Hernandez
14    Pamela   Castillo
15     Larry       Bott
16     Barry      Jones
17      Andy     Fixter
18     Peter      Marsh
19       Tom       King
20      Mami      Nishi
21   Yoshimi       Kato
22    Martin     Gerard

## Are there any offices that have zero employees?
Hint: Combine the employees and offices tables and use a group by. Select the office code, city, and number of employees.

In [8]:
# Your code here
q='''SELECT o.officeCode , o.city, COUNT(e.employeeNumber) AS number_of_employees FROM offices o
     LEFT JOIN employees e ON o.officeCode=e.officeCode GROUP BY o.officeCode, o.city'''
pd.read_sql(q,con)

   officeCode           city  number_of_employees
0           1  San Francisco                    6
1           2         Boston                    2
2           3            NYC                    2
3           4          Paris                    5
4           5          Tokyo                    2
5           6         Sydney                    4
6           7         London                    2
7          27         Boston                    0

## Write 3 questions of your own and answer them

In [9]:
"""
Question 1
"""
#Which Sale representative has the most customers?
q='''SELECT DISTINCT e.firstName, e.lastName, COUNT(c.customerNumber) AS total_employees FROM employees e JOIN customers c 
     ON e.employeeNumber=c.salesRepEmployeeNumber GROUP BY e.employeeNumber, e.firstName, e.lastName
     ORDER BY total_employees DESC LIMIT 1  '''
pd.read_sql(q,con)

  firstName  lastName  total_employees
0    Pamela  Castillo               10

In [10]:
"""
Question 2
"""
#Which product(s) are ordered frequently?
q='''SELECT p.productName, o.quantityOrdered FROM products p JOIN orderdetails o ON p.productCode=o.productCode
     ORDER BY quantityOrdered DESC LIMIT 1
    '''
pd.read_sql(q,con)

          productName  quantityOrdered
0  1969 Dodge Charger               97

In [11]:
"""
Question 3
"""

# Which customer left a comment
q='''SELECT c.customerName, o.comments FROM customers c JOIN orders o 
     ON c.customerNumber=o.customerNumber GROUP BY o.comments;'''

pd.read_sql(q,con)

,customerName,comments
0,Atelier graphique,
1,Euro+ Shopping Channel,I need all the information I can get on our c...
2,"Australian Collectors, Co.",Can we deliver the new Ford Mustang models by ...
3,Mini Gifts Distributors Ltd.,Can we renegotiate this one?
4,Euro+ Shopping Channel,Cautious optimism. We have happy customers her...
5,"Blauer See Auto, Co.",Check on availability.
6,Mini Gifts Distributors Ltd.,Custom shipping instructions sent to warehouse
7,Mini Gifts Distributors Ltd.,Custom shipping instructions were sent to ware...
8,Scandinavian Gift Ideas,Customer called to cancel. The warehouse was n...
9,Kelly's Gift Shop,Customer cancelled due to urgent budgeting iss...
10,Danish Wholesale Imports,Customer claims container with shipment was da...
11,"Australian Collectables, Ltd",Customer claims the scales of the models don't...
12,Tekni Collectables Inc.,Customer credit limit exceeded. Will ship when...
13,"UK Collectables, Ltd.",Customer disputed the order and we agreed to c...
14,Euro+ Shopping Channel,Customer doesn't like the colors and precision...
15,Daedalus Designs Imports,Customer has worked with some of our vendors i...
16,GiftsForHim.com,Customer heard complaints from their customers...
17,Enaco Distributors,Customer inquired about remote controlled mode...
18,Enaco Distributors,Customer is interested in buying more Ferrari ...
19,Muscle Machine Inc,Customer requested special shippment. The inst...
20,Euro+ Shopping Channel,Customer requested that DHL is used for this s...
21,Canadian Gift Exchange Network,Customer requested that FedEx Ground is used f...
22,"Volvo Model Replicas, Co",Customer requested that ad materials (such as ...
23,Signal Gift Stores,Customer very concerned about the exact color ...
24,Gifts4AllAges.com,Customer will send a truck to our local wareho...
25,Land of Toys Inc.,Difficult to negotiate with customer. We need ...
26,Euro+ Shopping Channel,Disputed then Resolved on 3/15/2005. Customer ...
27,Danish Wholesale Imports,Order was disputed and resolved on 12/1/04. Th...
28,Land of Toys Inc.,Order was mistakenly placed. The warehouse not...
29,"Volvo Model Replicas, Co",The outstaniding balance for this customer exc...
30,Mini Gifts Distributors Ltd.,They want to reevaluate their terms agreement ...
31,"Double Decker Gift Stores, Ltd",They want to reevaluate their terms agreement ...
32,Euro+ Shopping Channel,This customer found a better offer from one of...
33,Toys4GrownUps.com,This order was disputed and resolved on 2/1/20...
34,Mini Auto Werke,"This order was disputed, but resolved on 11/1/..."
35,"Dragon Souveniers, Ltd.",This order was on hold because customers's cre...
36,"Clover Collections, Co.",We must be cautions with this customer. Their ...
37,"Dragon Souveniers, Ltd.",We need to keep in close contact with their Ma...

## Level Up 1: Display the names of every individual product that each employee has sold

Hint: You will need to use multiple `JOIN` clauses to connect all the way from employee names to product names.

In [12]:
# Your code here
q='''SELECT p.productName,e.firstName, e.lastName FROM employees e
     JOIN customers c ON e.employeeNumber=c.salesRepEmployeeNumber 
     JOIN orders o ON c.customerNumber=o.customerNumber 
     JOIN orderdetails od ON o.orderNumber=od.orderNumber 
     JOIN products p ON p.productCode=od.productCode;'''
     #ORDER BY e.lastName, p.productName;'''
pd.read_sql(q,con)

                                      productName firstName  lastName
0                                  1958 Setra Bus    Leslie  Jennings
1                          1940 Ford Pickup Truck    Leslie  Jennings
2                         1939 Cadillac Limousine    Leslie  Jennings
3     1996 Peterbilt 379 Stake Bed with Outrigger    Leslie  Jennings
4                               1968 Ford Mustang    Leslie  Jennings
...                                           ...       ...       ...
2991                  1954 Greyhound Scenicruiser    Martin    Gerard
2992       1950's Chicago Surface Lines Streetcar    Martin    Gerard
2993             Diamond T620 Semi-Skirted Tanker    Martin    Gerard
2994                           1911 Ford Town Car    Martin    Gerard
2995             1936 Mercedes Benz 500k Roadster    Martin    Gerard

[2996 rows x 3 columns]

## Level Up 2: Display the number of products each employee has sold

Alphabetize the results by employee last name.

Hint: Use the `quantityOrdered` column from `orderDetails`. Also, think about how to group the data when some employees might have the same first or last name.

In [29]:
# Your code here
# Your code here
q='''SELECT 
    e.firstName,
    e.lastName,
    SUM(od.quantityOrdered) AS totalProductsSold
FROM employees e
JOIN customers c 
    ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders o 
    ON c.customerNumber = o.customerNumber
JOIN orderDetails od 
    ON o.orderNumber = od.orderNumber
GROUP BY
    e.employeeNumber,
    e.firstName,
    e.lastName
ORDER BY 
    e.lastName ASC;'''
pd.read_sql(q,con)

   firstName   lastName  totalProductsSold
0       Loui     Bondur               6186
1      Larry       Bott               8205
2     Pamela   Castillo               9290
3      Julie   Firrelli               4227
4       Andy     Fixter               6246
5     Martin     Gerard               4180
6     Gerard  Hernandez              14231
7     Leslie   Jennings              11854
8      Barry      Jones               7486
9      Peter      Marsh               6632
10      Mami      Nishi               4923
11     Steve  Patterson               5561
12    Leslie   Thompson               4056
13  Foon Yue      Tseng               5016
14    George     Vanauf               7423

## Level Up 3: Display the names employees who have sold more than 200 different products

Hint: this is different from the previous question because the quantity sold doesn't matter, only the number of different products

In [35]:
# Your code here
q='''SELECT e.firstName,e.lastName, COUNT(DISTINCT od.productCode) AS differentProductsSold
     FROM employees e
     JOIN customers c ON e.employeeNumber = c.salesRepEmployeeNumber
     JOIN orders o ON c.customerNumber = o.customerNumber
     JOIN orderdetails od ON o.orderNumber = od.orderNumber
     GROUP BY e.firstName,e.lastName,e.employeeNumber
     HAVING COUNT(DISTINCT od.productCode) > 200
     ORDER BY e.lastName ASC;'''
pd.read_sql(q, con)

Empty DataFrame
Columns: [firstName, lastName, differentProductsSold]
Index: []

## Summary

Congrats! You practiced using join statements and leveraged your foreign keys knowledge!